### ISSUE TITLE
Problems?

### ISSUE THREAD

**Issue by PandaWhoCodes** [deepak-asai/deepak#1]
This is kinda the template we used for flytta 
A Basic RoR App 
What errors were you facing on deploying it ?

**Comment by deepak-asai** [comment]
"git push heroku master" command is not wokirng.. so i tried to install
bundle bt its not working.. it s asking me to install separate gem file
again and again for continuing with "bundles install"..

https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
Virus-free.
www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by PandaWhoCodes** [comment]
do you know what the command means ?

**Comment by PandaWhoCodes** [comment]
https://devcenter.heroku.com/articles/git
Did you follow the procedure ?

**Comment by deepak-asai** [comment]
it is for merging the local branch with the master branch ryt?

https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
Virus-free.
www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by PandaWhoCodes** [comment]
please give that article a read

**Comment by deepak-asai** [comment]
yea i followed tat procedure only,, see

for this command am getting result like this..
C:\Sites\about-myself>heroku git:remote -a about-myself
set git remote heroku to https://git.heroku.com/about-myself.git

finally when i try to push heroku master am getting "push rejected"

**Comment by deepak-asai** [comment]
yeaaaa..!!

**Comment by deepak-asai** [comment]
heyy you have sent me the heroku app link ryt.. how to fork from it?

**Comment by PandaWhoCodes** [comment]
there is a fork button

**Comment by deepak-asai** [comment]
yeaaa i found.. see i download ror app from git hub and tried to install
deploy on heroku.. and am getting same problem.. it is asking to install
certain gem again and again.. i think so there must be a problem with my
ror software.. what shall i do??

https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
Virus-free.
www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by PandaWhoCodes** [comment]
i deployed it and had no issues :3 
Fork the project
click on the deploy link in the description

**Comment by deepak-asai** [comment]
oooooh..! :( dude which version ruby and rails u r using..? do you use in
windows?

https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
Virus-free.
www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by deepak-asai** [comment]
heyy... Am able to deploy tat in the way u said..! bt i cant do it for my
own application.. i ll try to figure it out by tday nyt..

**Comment by PandaWhoCodes** [comment]
cool 
add me on fb 
fb.com/reach2ashish
